# SPDX-FileCopyrightText: Alvar Penning
#
# SPDX-License-Identifier: BSD-3-Clause

name: CI

on: [push, pull_request]

jobs:
  golang:
    name: Check Go code

    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ 'oldstable', 'stable' ]

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - run: go version
    - run: go build ./...

    - uses: golangci/golangci-lint-action@v7

    - run: ./test/test.sh

  reuse:
    name: Check REUSE compliance

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: fsfe/reuse-action@v5
